name:                proyecto-vacio
version:             0.1.0.0
github:              "pdepjm/proyecto-vacio"
license:             BSD3
author:              "PdeP JM"
maintainer:          "pdepjm@googlegroups.com"
copyright:           "2020 PdeP JM"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdepjm/proyecto-vacio#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  proyecto-vacio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proyecto-vacio
    - hspec
